apiVersion: v1
kind: Secret
metadata:
  name: thesistrack-secrets
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | b64enc | quote }}
  {{- if .Values.email.smtpPassword }}
  SMTP_PASSWORD: {{ .Values.email.smtpPassword | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thesistrack-config
data:
  POSTGRES_SERVER: {{ .Values.postgres.service.name | quote }}
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | quote }}
  ENVIRONMENT: {{ .Values.environment | quote }}
  PROJECT_NAME: {{ .Values.projectName | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  VITE_GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  VITE_API_URL: {{ printf "https://%s/api" .Values.domain | quote }}
  {{- if .Values.email.smtpHost }}
  SMTP_HOST: {{ .Values.email.smtpHost | quote }}
  SMTP_PORT: {{ .Values.email.smtpPort | quote }}
  SMTP_USER: {{ .Values.email.smtpUser | quote }}
  EMAILS_FROM_EMAIL: {{ .Values.email.fromEmail | quote }}
  EMAILS_FROM_NAME: {{ .Values.email.fromName | quote }}
  {{- end }}
