"""Add location to deadline table

Revision ID: add_location_to_deadline
Revises: add_profile_picture
Create Date: 2025-01-10 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_location_to_deadline'
down_revision = 'add_profile_picture'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadline', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadline', 'location')
    # ### end Alembic commands ###
